const types = [
    "/Esturion_feb_09",
    "/Ipad_varias_2009",
    "/iPhone_Celia_2011",
    "/iPhone_Celia_2014",
    "/iPhone_Celia_2018",
    "/iPhone_Celia_A",
    "/Iphone_Celia_B",
    "/iPhone_Celia_C",
    "/iPhone_Celia_D",
    "/iPhone_Celia_E",
    "/Instagram",
    "/Instagram_A",
    "/Instagram_B",
    "/Instagram_C",
    "/Instagram_D",
    "/Instagram_E",
    "/Instagram_F",
    "/La_Tortuga_Agosto_2010",
    "/La_tortuga_octubre_2010",
    "/Miami_feb_2009",
    "/Oswaldo_A",
    "/Oswaldo_B",
    "/Oswaldo_C",
    "/Oswaldo_D",
    "/Oswaldo_E",
    "/Oswaldo_F",
    "/Oswaldo_G",
    "/uploads"
]

export { types }